name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-gnu

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ubuntu-latest-cargo-publish-${{ hashFiles('**/Cargo.lock') }}

    - name: Publish vte-ansi
      run: |
        cd crates/vte-ansi
        cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          See [CHANGELOG.md](https://github.com/hugomf/hugovte/blob/${{ github.sha }}/CHANGELOG.md) for release details.

          ## Installation

          ```toml
          [dependencies]
          vte-ansi = "0.1"
          ```
        draft: false
        prerelease: false

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: publish
    if: success()
    steps:
    - name: Notify Discord
      uses: rjstone/discord-webhook-notify@v1
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: "📦 vte-ansi ${{ github.ref_name }} released!"
        description: "New release published to crates.io"
        color: "0x00ff00"
        fields: |
          [
            {
              "name": "Release Notes",
              "value": "[View CHANGELOG](https://github.com/hugomf/hugovte/blob/${{ github.ref_name }}/CHANGELOG.md)",
              "inline": true
            },
            {
              "name": "Crates.io",
              "value": "[View on crates.io](https://crates.io/crates/vte-ansi)",
              "inline": true
            }
          ]
